# Copyright (C) 2024 Eccelerators GmbH
# 
# This code was generated by:
#
# HxS Compiler v0.0.0-0000000
# Python Extension for HxS 1.0.7-62bb9ef4
# 
# Further information at https://eccelerators.com/hxs
# 
# Changes to this file may cause incorrect behavior and will be lost if the
# code is regenerated.
	
	
# -----------------------------------------------------
# Addresses, widths, values and masks for direct access
# -----------------------------------------------------
EventCatcherIfcAddressBusWidth = 4
EventCatcherIfcDataBusWidth = 32

class EventCatcherBlk:
    EventCatcherBlkAddress = 0x0 
    EventCatcherBlkSize = 0xC 

    @property
    def EventMaskRegAddress(self):
        return (0x0 + self.EventCatcherBlkAddress)

    EventMaskRegWidth = 32

    MaskMask = 0x0000000F
    MaskPosition = 0
    MaskWidth = 4
    EventEnabledMVal = 0x00000001
    EventDisabledMVal = 0x00000000
    MaskBusResetMRstVal = 0x00000000


    @property
    def EventCatchRegAddress(self):
        return (0x4 + self.EventCatcherBlkAddress)

    EventCatchRegWidth = 32

    CatchMask = 0x0000000F
    CatchPosition = 0
    CatchWidth = 4
    CatchedMVal = 0x00000001
    NotCatchedMVal = 0x00000000
    Catch_ConfirmedMVal = 0x00000001
    Catch_InEffectiveMVal = 0x00000000
    Catch_AsyncMRstVal = 0x00000000


    @property
    def EventOverrunRegAddress(self):
        return (0x8 + self.EventCatcherBlkAddress)

    EventOverrunRegWidth = 32

    OverrunMask = 0x0000000F
    OverrunPosition = 0
    OverrunWidth = 4
    HappenedMVal = 0x00000001
    NotHappenedMVal = 0x00000000
    Overrun_ConfirmedMVal = 0x00000001
    Overrun_InEffectiveMVal = 0x00000000
    Overrun_AsyncMRstVal = 0x00000000
