/* Copyright (C) 2024 Eccelerators GmbH
   
   This code was generated by:
  
   HxS Compiler v0.0.0-0000000
   C Extension for HxS 1.0.24-85d98215
   
   Further information at https://eccelerators.com/hxs
   
   Changes to this file may cause incorrect behavior and will be lost if the
   code is regenerated.
*/	
	
#ifndef _EventCatcherIfc_H
#define _EventCatcherIfc_H

/* ----------------------------------------------------- */
/* Addresses, widths, values and masks for direct access */
/* ----------------------------------------------------- */
#define EventCatcherIfcAddressBusWidth 4
#define EventCatcherIfcDataBusWidth 32

#define EventCatcherBlkAddress 0x0
#define EventCatcherBlkSize 0xC

#define EventMaskRegAddress (0x0 + EventCatcherBlkAddress)
#define EventMaskRegWidth 32

#define MaskMask 0x0000000F
#define MaskPosition 0
#define MaskWidth 4
#define EventEnabledMVal 0x00000001
#define EventDisabledMVal 0x00000000
#define MaskBusResetMRstVal 0x00000000

#define EventCatchRegAddress (0x4 + EventCatcherBlkAddress)
#define EventCatchRegWidth 32

#define CatchMask 0x0000000F
#define CatchPosition 0
#define CatchWidth 4
#define CatchedMVal 0x00000001
#define NotCatchedMVal 0x00000000
#define Catch_ConfirmedMVal 0x00000001
#define Catch_InEffectiveMVal 0x00000000
#define Catch_AsyncMRstVal 0x00000000

#define EventOverrunRegAddress (0x8 + EventCatcherBlkAddress)
#define EventOverrunRegWidth 32

#define OverrunMask 0x0000000F
#define OverrunPosition 0
#define OverrunWidth 4
#define HappenedMVal 0x00000001
#define NotHappenedMVal 0x00000000
#define Overrun_ConfirmedMVal 0x00000001
#define Overrun_InEffectiveMVal 0x00000000
#define Overrun_AsyncMRstVal 0x00000000

#endif
